services:

  backend:
    build: .
    container_name: audiobot-backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/audiobot
    depends_on:
      - redis
      - db

  redis:
    image: redis/redis-stack:latest
    container_name: audiobot-redis
    ports:
      - "6379:6379"
      - "8001:8001" # RedisInsight UI

  db:
    image: postgres:15
    container_name: audiobot-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: audiobot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: audiobot-nginx
    ports:
      - "80:80"
    volumes:
      - ../frontend:/usr/share/nginx/html
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  postgres_data:
