[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "audiobot-backend"
version = "0.2.0"
description = "Backend for AudioBot using FastAPI and LangGraph"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]",
    "uvicorn",
    "langgraph",
    "langchain-core",
    "langchain-openai",
    "langchain-groq",
    "python-dotenv",
    "websockets",
    "langchain",
    "langchain-community",
    "redis",
    "langgraph-checkpoint-redis",
    "faster-whisper",
    "edge-tts",
    "pdfplumber",
    "pydantic",
    "email-validator",
    "python-multipart",
    "SQLAlchemy",
    "alembic",
    "asyncpg",
    "psycopg2-binary",
    "python-jose",
    "passlib[bcrypt]",
    "bcrypt<5",
    "numpy",
    "sounddevice",
    "soundfile",
    "reportlab",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["app*"]

[tool.fastapi]
entrypoint = "app.main:app"
