"""add_mock_interview_fields

Revision ID: 5b8c06e5c832
Revises: 20260415_0001
Create Date: 2026-05-01 13:21:15.926185
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '5b8c06e5c832'
down_revision = '20260415_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('interview_mode', sa.String(length=50), nullable=False, server_default='live'))
    op.add_column('interviews', sa.Column('interview_type', sa.String(length=50), nullable=True))
    op.add_column('interviews', sa.Column('difficulty', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'difficulty')
    op.drop_column('interviews', 'interview_type')
    op.drop_column('interviews', 'interview_mode')
    # ### end Alembic commands ###
